version: '3.4'

networks:
  demoapp:

services:
  desafiofinal:
    image: ${DOCKER_REGISTRY-}desafiofinal
    build:
      context: .
      dockerfile: DesafioFinal/Dockerfile
    ports:
      - "8080:80"
      - "5001:443"

  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=Numsey#2022
      - ACCEPT_EULA=Y
    volumes:
      - c:\dados\volumes\mssql:/var/opt/mssql/data   
    ports:
      - "1450:1433"  